### ISSUE TITLE
After first use of hotkey, it no longer works if closed with same hotkey.

### ISSUE THREAD

**Issue by MonstraG** [davidmhewitt/clipped#29]
1. Assign any hotkey to clipped.
2. Press the hotkey, clipped window appears.
3. Instead of selecting any of the clips, close window with same hotkey.
4. Press the hotkey again, to call clipped again. 

If I change hotkey to new one, I can repeat those four steps again.

**Comment by sergiubutnarasu** [comment]
@davidmhewitt  I did some debugging and I found that if I remove the key binding from Application.vala the problem disappear.

`keybinds.bind (get_paste_shortcut (), () => {
     close_window ();
});`

Maybe this could solve also https://github.com/davidmhewitt/clipped/issues/20 and https://github.com/davidmhewitt/clipped/issues/30

**Comment by brunnobb** [comment]
Same problem here. 
But in my case, the window does not open with in any case (except running by terminal again)

Fix on removing binding on window opening and closing also confirmed to work.
Did the dev added  this option just to close the window with the same shortcut? 

Should we commit a PR? This need a fix ASAP as it makes the app unusable. I can only use here after fixing.

**Comment by davidmhewitt** [comment]
Apologies for taking so long to get around to looking at this issue. I've never been able to reproduce it but your comments about removing the keybinding line and some extra help from a user in #30 has helped me narrow it down.

I believe that this issue should now be fixed in the `master` branch and will look to release a new version in the next few days that includes the fix. If any of you are able to test it before then and confirm whether it does or doesn't fix the issue, that would be much appreciated.

**Comment by davidmhewitt** [comment]
Version 1.1.1 has been released to the AppCenter and I believe this includes a fix for the shortcut key only working once.

As such, I'm going to close this issue, but please feel free to re-open it or add another comment if you're still experiencing this particular issue after updating.
